# Docker Compose override para desenvolvimento
# Use: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  api:
    # Monta c贸digo como volume para hot-reload
    volumes:
      - ./api:/app/api
      - ./shared:/app/shared
      - ./workers:/app/workers
      - ./tmp:/tmp/doc2md
    # Recarrega automaticamente quando c贸digo mudar
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1

  worker:
    # Monta c贸digo como volume para hot-reload
    volumes:
      - ./workers:/app/workers
      - ./shared:/app/shared
      - ./tmp:/tmp/doc2md
    # Recarrega automaticamente quando c贸digo mudar
    command: celery -A workers.celery_app worker --loglevel=info --concurrency=2 --pool=solo
    environment:
      - PYTHONUNBUFFERED=1
